// <auto-generated />
namespace Hospital_CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class doctorsupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorsupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202303252327495_doctors update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
