// <auto-generated />
namespace Hospital_CMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class doctorspecilization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorspecilization));
        
        string IMigrationMetadata.Id
        {
            get { return "202303190319241_doctor-specilization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
